GRANT SELECT  ON SERVIDOR TO TEEMO;
GRANT SELECT  ON DIVISION TO TEEMO;
GRANT SELECT  ON USUARIO TO TEEMO;
GRANT SELECT  ON RIOTER TO TEEMO;
GRANT SELECT  ON INVOCADOR TO TEEMO;
GRANT SELECT  ON REGION TO TEEMO;
GRANT SELECT  ON CARTA TO TEEMO;
GRANT SELECT  ON MAZO TO TEEMO;
GRANT SELECT  ON BATALLA TO TEEMO;

